[build]
  # This tells Netlify your website's files are in the "Website" folder.
  publish = "Website"
  # This tells Netlify where your serverless API functions are.
  functions = "Website/api"

# --- CORRECTED RULE ---
# This rule correctly routes all API requests to your serverless functions
# without interfering with static assets like your logo.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
