[build]
  # This tells Netlify your website's files are in the "Website" folder.
  publish = "Website"
  # This tells Netlify where your serverless API functions are.
  functions = "Website/api"

# --- NEW RULE TO FIX IMAGE PATHS ---
# This rule tells Netlify that any file it can't find (like /logo.gif)
# should be looked for inside the main publish directory.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200